name: NexEngine
main: su.nexmedia.engine.NexEngine
version: ${project.version}
description: NEX Plugin Engine
author: NEX-Media
softdepend: [Vault, WorldGuard, MythicMobs]
api-version: 1.14
load: STARTUP